spring.datasource.url=jdbc:mysql://localhost:3306/sales_savvy?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
salessavvy.jwt.secret=9a721adbd045bbca74f07c398616b11bc91l31fdb6693fc9d32c84e2764f69bad
salessavvy.jwt.expiration=86400000

server.port=8081
